from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QSlider, QLabel


class MyQSlider(QSlider):
    def __init__(self, parent=None, Window=None, name='', *args, **kwargs):
        super().__init__(parent, *args, **kwargs)
        self.name = QLabel(self)
        self.name.setText(name)
        # Qlabel在滑动条的父类下显示不全，直接父类设为主窗口
        if Window is not None:
            self.name.setParent(Window)
        self.name.resize(90, 35)
        if '横断面' in name:
            name_color = 'green'
            background_color = '#99ffcc'
        elif '冠状面' in name:
            name_color = 'blue'
            background_color = '#99ccff'
        elif '矢状面' in name:
            name_color = 'red'
            background_color = '#ff9999'
        else:
            name_color = 'black'
            background_color = 'white'

        self.name.setStyleSheet("font-family : 宋体,sans-serif;"
                                'font-weight: bold;'
                                "border-style: dashed;"
                                "border-width: 3px;"
                                + "border-color: {};".format(name_color)
                                + "background-color: {};".format(background_color)
                                + "color: {};".format(name_color))
        self.name.hide()

        label = QLabel(self)
        self.label = label
        label.setText('100')
        label.setStyleSheet('background-color:cyan;color:red')
        label.hide()

    def mousePressEvent(self, evt):
        super().mousePressEvent(evt)
        x = (((self.value() - self.minimum()) / (self.maximum() - self.minimum()))) * (
                self.width() - self.label.width())
        y = (self.height() - self.label.height()) / 2
        self.label.move(x, y)
        self.label.show()
        self.label.setText(str(self.value()))

    def mouseMoveEvent(self, evt):
        super().mouseMoveEvent(evt)
        x = (((self.value() - self.minimum()) / (self.maximum() - self.minimum()))) * (
                self.width() - self.label.width())
        y = (self.height() - self.label.height()) / 2
        self.label.move(x, y)
        self.label.setText(str(self.value()))
        self.label.adjustSize()

    def show_name(self):
        slider_x, slider_y = self.pos().x(), self.pos().y()
        self.name.move(slider_x + 65, slider_y + 210)
        self.name.show()

        x = (((self.value() - self.minimum()) / (self.maximum() - self.minimum()))) * (
                self.width() - self.label.width())
        y = (self.height() - self.label.height()) / 2
        self.label.move(x, y)
        self.label.setText(str(self.value()))
        self.label.adjustSize()
        self.label.show()


class Ui_APP_Window(object):
    def setupUi(self, APP_Window):
        APP_Window.setObjectName("APP_Window")
        APP_Window.resize(1200, 990)
        APP_Window.setMinimumSize(QtCore.QSize(800, 600))
        APP_Window.setMaximumSize(QtCore.QSize(1200, 990))
        self.centralwidget = QtWidgets.QWidget(APP_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 160, 1171, 777))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.A_L = MyQSlider(self.layoutWidget_2, APP_Window, '横断面窗位')
        self.A_L.setMouseTracking(False)
        self.A_L.setTabletTracking(False)
        self.A_L.setOrientation(QtCore.Qt.Horizontal)
        self.A_L.setObjectName("A_L")
        self.verticalLayout_4.addWidget(self.A_L)
        self.A_W = MyQSlider(self.layoutWidget_2, APP_Window, '横断面窗宽')
        self.A_W.setOrientation(QtCore.Qt.Horizontal)
        self.A_W.setObjectName("A_W")
        self.verticalLayout_4.addWidget(self.A_W)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.ViewA = QtWidgets.QGraphicsView(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ViewA.sizePolicy().hasHeightForWidth())
        self.ViewA.setSizePolicy(sizePolicy)
        self.ViewA.setMinimumSize(QtCore.QSize(384, 384))
        self.ViewA.setMaximumSize(QtCore.QSize(384, 384))
        self.ViewA.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ViewA.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ViewA.setObjectName("ViewA")
        self.gridLayout.addWidget(self.ViewA, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.C_L = MyQSlider(self.layoutWidget_2, APP_Window, '矢状面窗位')
        self.C_L.setOrientation(QtCore.Qt.Horizontal)
        self.C_L.setObjectName("C_L")
        self.verticalLayout_2.addWidget(self.C_L)
        self.C_W = MyQSlider(self.layoutWidget_2, APP_Window, '矢状面窗宽')
        self.C_W.setOrientation(QtCore.Qt.Horizontal)
        self.C_W.setObjectName("C_W")
        self.verticalLayout_2.addWidget(self.C_W)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.ViewC = QtWidgets.QGraphicsView(self.layoutWidget_2)
        self.ViewC.setMinimumSize(QtCore.QSize(384, 384))
        self.ViewC.setMaximumSize(QtCore.QSize(384, 384))
        self.ViewC.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ViewC.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ViewC.setObjectName("ViewC")
        self.gridLayout.addWidget(self.ViewC, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.PlaneA = MyQSlider(self.layoutWidget_2, APP_Window, '横断面序列')
        self.PlaneA.setMinimumSize(QtCore.QSize(120, 0))
        self.PlaneA.setOrientation(QtCore.Qt.Horizontal)
        self.PlaneA.setObjectName("PlaneA")
        self.verticalLayout.addWidget(self.PlaneA)
        self.PlaneB = MyQSlider(self.layoutWidget_2, APP_Window, '冠状面序列')
        self.PlaneB.setMinimumSize(QtCore.QSize(120, 0))
        self.PlaneB.setMouseTracking(False)
        self.PlaneB.setTabletTracking(False)
        self.PlaneB.setOrientation(QtCore.Qt.Horizontal)
        self.PlaneB.setObjectName("PlaneB")
        self.verticalLayout.addWidget(self.PlaneB)
        self.PlaneC = MyQSlider(self.layoutWidget_2, APP_Window, '矢状面序列')
        self.PlaneC.setMouseTracking(False)
        self.PlaneC.setTabletTracking(False)
        self.PlaneC.setOrientation(QtCore.Qt.Horizontal)
        self.PlaneC.setObjectName("PlaneC")
        self.verticalLayout.addWidget(self.PlaneC)
        self.gridLayout.addLayout(self.verticalLayout, 1, 2, 1, 1)
        self.ViewB = QtWidgets.QGraphicsView(self.layoutWidget_2)
        self.ViewB.setMinimumSize(QtCore.QSize(384, 384))
        self.ViewB.setMaximumSize(QtCore.QSize(384, 384))
        self.ViewB.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ViewB.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ViewB.setObjectName("ViewB")
        self.gridLayout.addWidget(self.ViewB, 0, 3, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.B_L = MyQSlider(self.layoutWidget_2, APP_Window, '冠状面窗位')
        self.B_L.setOrientation(QtCore.Qt.Horizontal)
        self.B_L.setObjectName("B_L")
        self.verticalLayout_3.addWidget(self.B_L)
        self.B_W = MyQSlider(self.layoutWidget_2, APP_Window, '冠状面窗宽')
        self.B_W.setOrientation(QtCore.Qt.Horizontal)
        self.B_W.setObjectName("B_W")
        self.verticalLayout_3.addWidget(self.B_W)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.ViewCUB = QtWidgets.QGraphicsView(self.layoutWidget_2)
        self.ViewCUB.setObjectName("ViewCUB")
        self.gridLayout.addWidget(self.ViewCUB, 1, 3, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(380, 10, 391, 141))
        self.textBrowser.setObjectName("textBrowser")
        APP_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(APP_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        self.open_files = QtWidgets.QMenu(self.menubar)
        self.open_files.setObjectName("open_files")
        self.save = QtWidgets.QMenu(self.menubar)
        self.save.setObjectName("save")
        self.helps = QtWidgets.QMenu(self.menubar)
        self.helps.setObjectName("helps")
        self.labels = QtWidgets.QMenu(self.menubar)
        self.labels.setObjectName("labels")
        APP_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(APP_Window)
        self.statusbar.setObjectName("statusbar")
        APP_Window.setStatusBar(self.statusbar)
        self.saveA = QtWidgets.QAction(APP_Window)
        self.saveA.setObjectName("saveA")
        self.saveB = QtWidgets.QAction(APP_Window)
        self.saveB.setObjectName("saveB")
        self.saveC = QtWidgets.QAction(APP_Window)
        self.saveC.setObjectName("saveC")
        self.file_path = QtWidgets.QAction(APP_Window)
        self.file_path.setObjectName("file_path")
        self.dir_path = QtWidgets.QAction(APP_Window)
        self.dir_path.setObjectName("dir_path")
        self.saveCUB = QtWidgets.QAction(APP_Window)
        self.saveCUB.setObjectName("saveCUB")
        self.saveAll = QtWidgets.QAction(APP_Window)
        self.saveAll.setObjectName("saveAll")
        self.actionhelp = QtWidgets.QAction(APP_Window)
        self.actionhelp.setObjectName("actionhelp")
        self.actionabout_us = QtWidgets.QAction(APP_Window)
        self.actionabout_us.setObjectName("actionabout_us")
        self.LabelPlaneA = QtWidgets.QAction(APP_Window)
        self.LabelPlaneA.setObjectName("LabelPlaneA")
        self.LabelPlaneB = QtWidgets.QAction(APP_Window)
        self.LabelPlaneB.setObjectName("LabelPlaneB")
        self.LabelPlaneC = QtWidgets.QAction(APP_Window)
        self.LabelPlaneC.setObjectName("LabelPlaneC")
        self.open_files.addAction(self.file_path)
        self.open_files.addAction(self.dir_path)
        self.save.addAction(self.saveA)
        self.save.addAction(self.saveB)
        self.save.addAction(self.saveC)
        self.save.addAction(self.saveCUB)
        self.save.addAction(self.saveAll)
        self.helps.addAction(self.actionhelp)
        self.helps.addAction(self.actionabout_us)
        self.labels.addAction(self.LabelPlaneA)
        self.labels.addAction(self.LabelPlaneB)
        self.labels.addAction(self.LabelPlaneC)
        self.menubar.addAction(self.open_files.menuAction())
        self.menubar.addAction(self.save.menuAction())
        self.menubar.addAction(self.labels.menuAction())
        self.menubar.addAction(self.helps.menuAction())

        self.retranslateUi(APP_Window)
        QtCore.QMetaObject.connectSlotsByName(APP_Window)

    def retranslateUi(self, APP_Window):
        _translate = QtCore.QCoreApplication.translate
        APP_Window.setWindowTitle(_translate("APP_Window", "CT成像显示系统"))
        self.open_files.setTitle(_translate("APP_Window", "打开"))
        self.save.setTitle(_translate("APP_Window", "图像保存"))
        self.helps.setTitle(_translate("APP_Window", "帮助"))
        self.labels.setTitle(_translate("APP_Window", "图像标注"))
        self.saveA.setText(_translate("APP_Window", "横断面图像"))
        self.saveB.setText(_translate("APP_Window", "矢状面图像"))
        self.saveC.setText(_translate("APP_Window", "冠状面图像"))
        self.file_path.setText(_translate("APP_Window", "文件路径"))
        self.dir_path.setText(_translate("APP_Window", "文件夹路径"))
        self.saveCUB.setText(_translate("APP_Window", "三维示意图"))
        self.saveAll.setText(_translate("APP_Window", "全选"))
        self.actionhelp.setText(_translate("APP_Window", "使用说明"))
        self.actionabout_us.setText(_translate("APP_Window", "关于我们"))
        self.LabelPlaneA.setText(_translate("APP_Window", "横断面图像"))
        self.LabelPlaneB.setText(_translate("APP_Window", "矢状面图像"))
        self.LabelPlaneC.setText(_translate("APP_Window", "冠状面图像"))
