# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Label_APP.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1018, 820)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1018, 26))
        self.menubar.setObjectName("menubar")
        self.Labelmenu = QtWidgets.QMenu(self.menubar)
        self.Labelmenu.setObjectName("Labelmenu")
        self.Savemenu = QtWidgets.QMenu(self.menubar)
        self.Savemenu.setObjectName("Savemenu")
        self.Helpmenu = QtWidgets.QMenu(self.menubar)
        self.Helpmenu.setObjectName("Helpmenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.actionabout_us = QtWidgets.QAction(MainWindow)
        self.actionabout_us.setObjectName("actionabout_us")
        self.actionpath_choose = QtWidgets.QAction(MainWindow)
        self.actionpath_choose.setObjectName("actionpath_choose")
        self.Savemenu.addAction(self.actionpath_choose)
        self.Helpmenu.addAction(self.actionhelp)
        self.Helpmenu.addAction(self.actionabout_us)
        self.menubar.addAction(self.Labelmenu.menuAction())
        self.menubar.addAction(self.Savemenu.menuAction())
        self.menubar.addAction(self.Helpmenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CT图像标注系统"))
        self.Labelmenu.setTitle(_translate("MainWindow", "标注管理"))
        self.Savemenu.setTitle(_translate("MainWindow", "标注图像保存"))
        self.Helpmenu.setTitle(_translate("MainWindow", "帮助"))
        self.actionhelp.setText(_translate("MainWindow", "使用帮助"))
        self.actionabout_us.setText(_translate("MainWindow", "关于我们"))
        self.actionpath_choose.setText(_translate("MainWindow", "路径选择"))
